# Generated by Django 4.1.7 on 2023-03-29 08:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Census',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255)),
                ('middle_name', models.CharField(blank=True, max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('date_of_birth', models.DateField()),
                ('phone_number', models.CharField(max_length=20)),
                ('house_address', models.CharField(max_length=255)),
                ('residential_building', models.CharField(blank=True, max_length=255)),
                ('lga_of_residence', models.CharField(max_length=255)),
                ('state_of_residence', models.CharField(max_length=255)),
                ('lga_of_origin', models.CharField(max_length=255)),
                ('state_of_origin', models.CharField(max_length=255)),
                ('occupation', models.CharField(blank=True, max_length=255)),
                ('place_of_work', models.CharField(blank=True, max_length=255)),
                ('level_of_education', models.CharField(blank=True, max_length=255)),
                ('type_of_family', models.CharField(blank=True, max_length=255)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
