# Generated by Django 4.1.7 on 2023-03-30 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('census', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='census',
            name='marital_status',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
